name: "Roam Research backup"

on:
  push:
    branches:
      - master
  schedule:
    - cron: "*/10 * * * *" 

jobs:
  backup:
    runs-on: macos-latest # trying to workaound random crashes on linux
    name: Backup
    timeout-minutes: 15
    steps:
      - name: Checkout notes repo
        uses: actions/checkout@v2
        with:
          repository: ${{ secrets.TARGETREPO }}
          token: ${{ secrets.ROAMRESEARCH_PAT }}
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      
      - name: Setup dependencies
        run: |
          brew install borkdude/brew/jet # to do edn formatting. Note: MacOs specific
          pip install git+https://github.com/Stvad/roam-to-git.git@edn
      - name: Run backup
        run: |
          roam-to-git . --formats json edn
        env:
          ROAMRESEARCH_USER: ${{ secrets.ROAMRESEARCH_USER }}
          ROAMRESEARCH_PASSWORD: ${{ secrets.ROAMRESEARCH_PASSWORD }}
          ROAMRESEARCH_DATABASE: ${{ secrets.ROAMRESEARCH_DATABASE }}
          
